"""empty message

Revision ID: acb2bbdb1ac5
Revises: 7cd41babb967
Create Date: 2022-02-25 14:50:06.683409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb2bbdb1ac5'
down_revision = '7cd41babb967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('left_index', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('right_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'right_index')
    op.drop_column('comments', 'left_index')
    # ### end Alembic commands ###
